### ISSUE TITLE
Standard configuration causes never ending rerun.

### ISSUE THREAD

**Issue by Philwi** [Sorc96/rspec-watcher#1]
Hey,

thanks for the gem! There is indeed the need for instance feedback while TDD. So I am enjoying this approach very much. :)

But I think there is a problem with the standard configuration:

https://github.com/Sorc96/rspec-watcher/blob/988e7d6cdf0c4d62b9f59dc9e6d2b8e506ceb898/lib/rspec_watcher/default_configuration.rb#L8

I am using `config.example_status_persistence_file_path="./spec/examples.txt"`. It is the standard configuration for persisting the results for each example. It is necessary for the feature `--only-failures` and I guess many are using this. 

So maybe we should adjust this line, to ignore this standard examples file? 

I tried to delete this line for my initializer to get rid of it. But sadly, it always uses the standard configuration.

**Comment by Sorc96** [comment]
Thanks for checking this gem out!

Overriding the default configuration should work, but of course, I could have messed something up. I'm going to check it tomorrow.

I didn't think of `examples.txt`, that certainly breaks the rule. My idea with this line was to catch changes to files like `spec_helper.rb` or various things in `support` and fixtures/factories, but maybe that shouldn't be the default.

In fact, maybe the default should be to only react to changes in specs. I wanted to make it as easy as possible to start using the gem, but the current defaults assume a very standard Rails setup, so they most likely will not work that well for a lot of people. Maybe it would be better to include this config as an example for people to copy into their project if they want to.

We could also make an exception just for `examples.txt`. I'm probably going to start with that and decide how to deal with the rest if there is more feedback from others.

**Comment by Sorc96** [comment]
Should be fixed now in 0.3.2. If there is an `examples.txt` file somewhere in 'spec', it will get ignored, and custom configuration should work as well.
